// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // CLI-only connection (migrate, studio, db pull). Uses the direct
  // (non-pooled) URL since PgBouncer transaction pooling doesn't support
  // the prepared statements migrations need. The app's runtime client
  // (src/lib/prisma.ts) connects via the pooled DATABASE_URL instead.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
